INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (1,'Subaru');
INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (2,'Mercedes-Benz');
INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (3,'Chevrolet');
INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (4,'Toyota');
INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (5,'Honda');
INSERT INTO tb_marca (MARCA_ID,NOME_MARCA) VALUES (6,'Nissan');

INSERT INTO TB_MODELO (MODELO_ID,MARCA_ID, NOME, VALOR_FIPE) VALUES (1,4, 'Toyota Supra', 120000.00);
INSERT INTO TB_MODELO (MODELO_ID,MARCA_ID, NOME, VALOR_FIPE) VALUES (2,4, 'Toyota Corolla', 50000.00);
INSERT INTO TB_MODELO (MODELO_ID,MARCA_ID, NOME, VALOR_FIPE) VALUES (3,4, 'Toyota Etios', 60000.00);

INSERT INTO TB_MODELO (MODELO_ID,MARCA_ID, NOME, VALOR_FIPE) VALUES (4,2, 'Mercedes-GLA', 150000.00);
INSERT INTO TB_MODELO (MODELO_ID,MARCA_ID, NOME, VALOR_FIPE) VALUES (5,2, 'Mercedes-CLA', 100000.00);

INSERT INTO TB_CARRO (ID,TIME_STAMP_CADASTRO, MODELO_ID, ANO, COMBUSTIVEL, NUM_PORTAS, COR) VALUES (1,'2023-10-13', 1, '2023', 'FLEX', 4, 'VERMELHO');